### ISSUE TITLE
The "about" page is still fake Latin

### ISSUE THREAD

**Issue by jcayzac** [rakutentech/engineering-blog#15]
https://github.com/rakutentech/engineering-blog/blob/main/content/about.md still has placeholder content.

**Comment by boazy** [comment]
I was coming to say Lorem Ipsum is not fake Latin, but actually, it's a mashup of sentences from Cicero's _De finibus bonorum et malorum_ (It's _dolorem ipsum, quia dolor sit amet..._).

But I see it's not even Lorem ipsum. I suggest we change to something different, probably Cataullus. One of his less offensive things. Perhaps Vergilius if we want to be pompous.
